### ISSUE TITLE
pip install pylastfm==0.1.0 failes due to lack of README.md file

### ISSUE THREAD

**Issue by dahlia** [thesquelched/pylastfm#7]
Seems the sdist uploaded to PyPI is missing README.md file.

```console
$ pip install -e .
Obtaining file:///.../Projects/seasonal-mixes
Collecting pylastfm<0.2.0,>=0.1.0 (from ...)
  Downloading pylastfm-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-5m85lx5w/pylastfm/setup.py", line 28, in <module>
        with open(README) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5m85lx5w/pylastfm/README.md'
```

**Comment by thesquelched** [comment]
Fixed in pypi 0.1.1 release.
